__name__ = "flatten"
__version__ = "0.0.1"
__description__ = "Image Compression using Digital Signal Processing"
__url__ = "https://github.com/gavindsouza/flatten"
__author__ = r"Gavin D'souza"
__email__ = "gavin18d@gmail.com"
__license__ = "MIT"
